#!/usr/bin/env bash


if [ $# -ge 1 ]; then
    fullname="${1//://}"
#    IFS=':' read -a cmd <<< "${1}"
#    file=${cmd[0]}
    if [ ! -f "devtools/$fullname.sh" ]; then
        echo "devtools/$fullname.sh not found"
        $0 | grep $1
        exit 0
    else
        sh "devtools/$1.sh" $0 $*
    fi
else
    sh devtools/--help.sh $0
fi


#
#case $1 in
#    "init")
#    ;;
#    " ")
#        echo 'shir'
#    ;;
#    *)
#        if [ $# -eq 1 ]
#        then
#            $0 | grep $1
#        else
#            sh devtools/usage.sh $*
#        fi
#   ;;
#esac